import type { Metadata } from "next";
import "./globals.css";
import { fontSans, fontSerif } from "@/lib/fonts";
import NavBar from "@/components/shared/nav-bar";

export const metadata: Metadata = {
  title: "Aditya Nandan - Software Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${fontSans.variable} ${fontSerif.variable} antialiased font-sans dark`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
